"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api, Bag } from "@/lib/client/api";

type EditableBag = Bag & { _count: { orders: number } };
function localValue(iso: string) { const date = new Date(iso); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
export default function EditBusinessBagPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [bag, setBag] = useState<EditableBag | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { api<{ bag: EditableBag }>(`/api/business/bags/${id}`).then(({ bag }) => setBag(bag)).catch((e) => setError(e instanceof Error ? e.message : "Не удалось загрузить пакет")); }, [id]);
  function set(key: keyof EditableBag, value: string | number) { setBag((current) => current ? { ...current, [key]: value } : current); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!bag) return; setBusy(true); setError(null); try { await api(`/api/business/bags/${id}`, { method: "PATCH", body: JSON.stringify({ action: "details", title: bag.title, description: bag.description, allergens: bag.allergens, price: Number(bag.price), originalPrice: Number(bag.originalPrice), pickupStart: bag.pickupStart, pickupEnd: bag.pickupEnd }) }); router.push("/business/bags"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось сохранить пакет"); setBusy(false); } }
  if (!bag) return <main className="mx-auto max-w-2xl p-5"><Link href="/business/bags" className="text-sm font-semibold text-primary">← К пакетам</Link><p className="mt-6 text-sm text-muted">{error ?? "Загрузка…"}</p></main>;
  const closed = !["ACTIVE", "SOLD_OUT"].includes(bag.status);
  return <main className="mx-auto max-w-2xl space-y-5 p-5 sm:pt-6"><header><Link href="/business/bags" className="text-sm font-semibold text-primary">← К пакетам</Link><h1 className="mt-3 text-2xl font-bold">Редактирование пакета</h1><p className="mt-1 text-sm text-muted">Заказов: {bag._count.orders}. После первой покупки цена и время фиксируются.</p></header><form onSubmit={save} className="space-y-4 rounded-2xl border bg-white p-5"><label className="block text-sm font-medium">Название<input disabled={closed} value={bag.title} onChange={(e) => set("title", e.target.value)} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label><label className="block text-sm font-medium">Примерный состав<textarea disabled={closed} value={bag.description} onChange={(e) => set("description", e.target.value)} rows={3} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label><label className="block text-sm font-medium">Возможные аллергены<input disabled={closed} value={bag.allergens} onChange={(e) => set("allergens", e.target.value)} placeholder="Глютен, молоко, яйца, орехи" className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /><span className="mt-1 block text-xs font-normal text-muted">Укажите всё возможное: фактический состав пакета может меняться.</span></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium">Цена FoodGood<input disabled={closed} type="number" value={bag.price} onChange={(e) => set("price", Number(e.target.value))} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label><label className="block text-sm font-medium">Минимальная обычная стоимость<input disabled={closed} type="number" value={bag.originalPrice} onChange={(e) => set("originalPrice", Number(e.target.value))} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-medium">Начало выдачи<input disabled={closed} type="datetime-local" value={localValue(bag.pickupStart)} onChange={(e) => set("pickupStart", new Date(e.target.value).toISOString())} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label><label className="block text-sm font-medium">Конец выдачи<input disabled={closed} type="datetime-local" value={localValue(bag.pickupEnd)} onChange={(e) => set("pickupEnd", new Date(e.target.value).toISOString())} className="mt-1 w-full rounded-xl border p-3 disabled:bg-black/[0.04]" /></label></div>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={busy || closed} className="w-full rounded-xl bg-primary p-3 font-bold text-white disabled:opacity-50">{busy ? "Сохраняем…" : "Сохранить"}</button></form></main>;
}
