"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/client/api";

type Partner = { id: string; legalType: string | null; legalName: string | null; businessIdentifier: string | null; contactName: string | null; contactPhone: string | null; verificationStatus: string; verificationNote: string | null; verifiedAt: string | null; owner: { name: string | null; phone: string | null; venues: { id: string; name: string; category: string; status: string }[] }; agreements: { agreementVersion: string; acceptedAt: string }[] };
const labels: Record<string, string> = { PENDING: "На проверке", VERIFIED: "Проверен", REJECTED: "Отклонён", SUSPENDED: "Приостановлен" };

export default function AdminPartnerPage() {
  const { id } = useParams<{ id: string }>(); const [partner, setPartner] = useState<Partner | null>(null); const [currentVersion, setCurrentVersion] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(() => api<{ partner: Partner; agreementVersion: string }>(`/api/admin/partners/${id}`).then(({ partner, agreementVersion }) => { setPartner(partner); setCurrentVersion(agreementVersion); setNote(partner.verificationNote ?? ""); }).catch((e) => setError(e instanceof Error ? e.message : "Не удалось загрузить партнёра")), [id]);
  useEffect(() => { load(); }, [load]);
  async function moderate(action: "approve" | "reject" | "suspend") { setBusy(true); setError(null); setMessage(null); try { await api(`/api/admin/partners/${id}`, { method: "PATCH", body: JSON.stringify({ action, note }) }); await load(); setMessage(action === "approve" ? "Партнёр допущен к публикации." : action === "reject" ? "Заявка отклонена." : "Публикация партнёра приостановлена."); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось изменить статус"); } finally { setBusy(false); } }
  if (!partner) return <main className="mx-auto max-w-3xl p-4 sm:p-6"><Link href="/admin/partners" className="text-sm font-semibold text-primary">← К партнёрам</Link><p className="mt-6 text-sm text-muted">{error ?? "Загрузка…"}</p></main>;
  const currentAgreement = partner.agreements.find(({ agreementVersion }) => agreementVersion === currentVersion);
  return <main className="mx-auto max-w-3xl space-y-5 p-4 sm:p-6"><header><Link href="/admin/partners" className="text-sm font-semibold text-primary">← К партнёрам</Link><h1 className="mt-2 text-2xl font-bold">{partner.legalName ?? "Партнёр без заполненных данных"}</h1><p className="mt-1 text-sm text-muted">Статус: <b>{labels[partner.verificationStatus] ?? partner.verificationStatus}</b></p></header>{message && <p role="status" className="rounded-xl bg-green-50 p-3 text-sm text-green-800">{message}</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2"><Datum label="Форма" value={partner.legalType === "IP" ? "ИП" : partner.legalType === "TOO" ? "ТОО" : null} /><Datum label="БИН/ИИН" value={partner.businessIdentifier} /><Datum label="Контакт" value={partner.contactName} /><Datum label="Телефон" value={partner.contactPhone} /><Datum label="Аккаунт" value={partner.owner.name ?? partner.owner.phone} /><Datum label="Текущий договор" value={currentAgreement ? `Принят ${new Date(currentAgreement.acceptedAt).toLocaleString("ru-RU")}` : "Не принят"} /></section><section className="rounded-2xl border bg-white p-4"><h2 className="font-semibold">Заведения</h2><div className="mt-3 space-y-2">{partner.owner.venues.length === 0 ? <p className="text-sm text-muted">Нет заведений.</p> : partner.owner.venues.map((venue) => <Link key={venue.id} href={`/admin/venues/${venue.id}`} className="flex justify-between rounded-xl border p-3 text-sm"><span>{venue.name}</span><span className="text-muted">{venue.category} · {venue.status}</span></Link>)}</div></section><section className="space-y-3 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Решение</h2><label className="block text-sm font-medium">Комментарий<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={3} placeholder="Обязателен для отклонения и приостановки" className="mt-1 w-full rounded-xl border p-3" /></label><div className="grid gap-2 sm:grid-cols-3"><button disabled={busy || partner.verificationStatus === "VERIFIED" || !currentAgreement} onClick={() => moderate("approve")} className="rounded-xl bg-primary px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Одобрить</button><button disabled={busy || !note.trim()} onClick={() => moderate("reject")} className="rounded-xl border border-red-200 px-3 py-2.5 text-sm font-semibold text-red-700 disabled:opacity-40">Отклонить</button><button disabled={busy || !note.trim()} onClick={() => moderate("suspend")} className="rounded-xl border border-amber-300 px-3 py-2.5 text-sm font-semibold text-amber-800 disabled:opacity-40">Приостановить</button></div></section></main>;
}

function Datum({ label, value }: { label: string; value: string | null }) { return <div><p className="text-xs font-semibold text-muted">{label}</p><p className="mt-1 text-sm">{value || "Не заполнено"}</p></div>; }
