import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getBusinessAccess } from "@/modules/auth/business";
import BusinessBagActions from "@/components/BusinessBagActions";

function price(value: number) { return `${value.toLocaleString("ru-RU")} ₸`; }
const LABELS: Record<string, string> = { ACTIVE: "В продаже", SOLD_OUT: "Распродано", EXPIRED: "Истёк", CANCELLED: "Снят с продажи" };
export default async function BusinessBagsPage() { const { actor, owner } = await getBusinessAccess(); if (!owner) redirect(actor?.role === "ADMIN" ? "/admin/owners?select=1" : "/"); const bags = await prisma.bag.findMany({ where: { venue: { ownerId: owner.id } }, include: { venue: true, _count: { select: { orders: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold">Пакеты-сюрпризы</h1><p className="mt-1 text-sm text-muted">Следите за продажами и уменьшайте доступный остаток.</p></div><Link href="/business/new" className="rounded-xl bg-primary px-4 py-2.5 text-center text-sm font-semibold text-white">+ Новый пакет</Link></header>{bags.length === 0 ? <section className="rounded-2xl border bg-white p-8 text-center"><p className="font-semibold">Пакетов пока нет</p><p className="mt-1 text-sm text-muted">Опубликуйте излишки — они сразу появятся у покупателей.</p></section> : <section className="grid min-w-0 gap-4 md:grid-cols-2">{bags.map((bag) => { const editable = ["ACTIVE", "SOLD_OUT"].includes(bag.status) && bag.pickupEnd > new Date(); return <article key={bag.id} className="min-w-0 overflow-hidden rounded-2xl border bg-white p-4"><div className="flex min-w-0 justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{bag.title}</p><p className="truncate text-xs text-muted">{bag.venue.name}</p></div><span className={`h-fit shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${bag.status === "ACTIVE" ? "bg-green-50 text-green-700" : "bg-black/[0.05] text-muted"}`}>{LABELS[bag.status] ?? bag.status}</span></div><div className="mt-4 grid min-w-0 grid-cols-3 gap-2 text-sm"><div className="min-w-0"><p className="text-xs text-muted">Цена</p><p className="truncate font-semibold">{price(bag.price)}</p></div><div className="min-w-0"><p className="text-xs text-muted">Остаток</p><p className="font-semibold">{bag.quantityLeft}/{bag.quantityTotal}</p></div><div className="min-w-0"><p className="text-xs text-muted">Заказы</p><p className="font-semibold">{bag._count.orders}</p></div></div><p className="mt-3 truncate text-xs text-muted">Выдача: {new Date(bag.pickupStart).toLocaleString("ru-RU")}–{new Date(bag.pickupEnd).toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" })}</p><BusinessBagActions id={bag.id} quantityLeft={bag.quantityLeft} editable={editable} /></article>; })}</section>}</main>; }
